### ISSUE TITLE
I Made A Calculator App With Beautiful UI

### ISSUE THREAD

**Issue by Harshith1263** [Safnaj/Flutter-UI-Samples#15]
Sir is this Repo Participating in Hactoberfest 2022 ??
Because There are No Pull Requests till Now !!
If this Repo is in Hactoberfest 2022, I will give my Proposal of a Calculator app Made by me if u Like it U Can Merge it, Sir...

**Comment by Safnaj** [comment]
> Sir is this Repo Participating in Hactoberfest 2022 ?? Because There are No Pull Requests till Now !! If this Repo is in Hactoberfest 2022, I will give my Proposal of a Calculator app Made by me if u Like it U Can Merge it, Sir...

Go ahead. Pls follow the guideline by having ur screenshot in the ReadMe

**Comment by Harshith1263** [comment]
Ok, Sir Sure!!
